# Generated by Django 2.1.2 on 2018-12-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellpoint.Productos'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellpoint.Zona'),
        ),
    ]
