# Generated by Django 2.1.2 on 2018-11-30 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellpoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria_productos',
            old_name='nombre_categoria',
            new_name='categoria',
        ),
    ]
