# Generated by Django 2.1.2 on 2018-11-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellpoint', '0002_auto_20181130_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.BinaryField(blank=True),
        ),
    ]
