# Generated by Django 2.1.2 on 2018-11-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellpoint', '0003_auto_20181130_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores_clientes',
            old_name='nombre_comencial',
            new_name='nombre_comercial',
        ),
    ]
