# Generated by Django 2.1.3 on 2018-12-02 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellpoint', '0004_auto_20181130_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='zona',
        ),
        migrations.AddField(
            model_name='zona',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sellpoint.Almacen'),
            preserve_default=False,
        ),
    ]
